FROM node:12.17.0-alpine AS base
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --production
COPY . ./
RUN npm run build

FROM node:12.17.0-alpine AS final
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --production
COPY --from=base /usr/src/app/dist/ dist/
EXPOSE 3000
CMD ["node", "dist/index.js"]